*If running in Colab run this first to install ACN-Portal.*

In [2]:
import subprocess
import sys

# if 'google.colab' in str(get_ipython()):
#     print('Running on CoLab')
#     subprocess.check_call([sys.executable, "-m", "pip", "install", "acnportal"])
#     subprocess.check_call([sys.executable, "-m", "pip", "install", "git+https://github.com/caltech-netlab/adacharge"])

# Unbalanced Three-Phase Infrastructure Constraints

Currently, most charging algorithms in the literature rely on constraints which assume single-phase or balanced three-phase operation. In this experiment, we demonstrate why these assumptions are insufficient for practical charging systems. 

For this experiment we use the consider two algorithms, 1) least-laxity first (LLF) and 2) Model Predictive Control (MPC). We also consider two cases, in the first we use a simplified single-phase representation of the constraints in the network. In the second, we use the full three-phase system model. In both cases, we evalaute the algorithms using the true three-phase network model.

In [3]:
import pytz
from datetime import datetime
import numpy as np
# import cvxpy as cp
from copy import deepcopy
import time 
from matplotlib import pyplot as plt
from matplotlib import cm

from acnportal import acnsim
from acnportal.acnsim import analysis
from acnportal import algorithms
import adacharge

## Single-phase CaltechACN Network

In this *ChargingNetwork* we treat all EVSEs as if they were on the same phase by setting the phase angle for each to be 0. The only constraints for this model are that the aggregate rates of the AV and CC pods are less than 80 A and that the aggregate power of all EVSEs is less than the power limit of the transformer. 

(We assume nominal voltage in the network)

In [4]:
def single_phase_caltech_acn(basic_evse=False, voltage=208, transformer_cap=150, network_type=acnsim.ChargingNetwork):
    """ Predefined single phase ChargingNetwork for the Caltech ACN.

    Args:
        basic_evse (bool): If True use BASIC EVSE type instead of actual AeroViroment and ClipperCreek types.
        voltage (float): Default voltage at the EVSEs. Does not affect the current rating of the transformer which is
            based on nominal voltages in the network. 277V LL for delta primary and 120V LN for wye secondary. [V]
        transformer_cap (float): Capacity of the transformer in the CaltechACN. Default: 150. [kW]

    Attributes:
        See ChargingNetwork for Attributes.
    """
    network = network_type()

    if basic_evse:
        evse_type = {'AV': 'BASIC', 'CC': 'BASIC'}
    else:
        evse_type = {'AV': 'AeroVironment', 'CC': 'ClipperCreek'}
        
    # Define the sets of EVSEs in the Caltech ACN.
    CC_pod_ids = ["CA-322", "CA-493", "CA-496", "CA-320", "CA-495", "CA-321", "CA-323", "CA-494"]
    AV_pod_ids = ["CA-324", "CA-325","CA-326","CA-327","CA-489", "CA-490", "CA-491", "CA-492"]
    other_ids = [f"CA-{id_num}" for id_num in [148, 149, 212, 213, 303, 304, 305, 306, 307, 308,
                                               309, 310, 311, 312, 313, 314, 315, 316, 317, 318,
                                               319, 497, 498, 499, 500, 501, 502, 503, 504, 505,
                                               506, 507, 508, 509, 510, 511, 512, 513]]
    all_ids = CC_pod_ids + AV_pod_ids + other_ids

    # Add Caltech EVSEs
    for evse_id in all_ids:
        if evse_id not in CC_pod_ids:
            network.register_evse(acnsim.get_evse_by_type(evse_id, evse_type['AV']), voltage, 0)
        else:
            network.register_evse(acnsim.get_evse_by_type(evse_id, evse_type['CC']), voltage, 0)
            
    # Add Caltech Constraint Set
    CC_pod = acnsim.Current(CC_pod_ids)
    AV_pod = acnsim.Current(AV_pod_ids)
    all_current = acnsim.Current(all_ids)

    # Build constraint set
    network.add_constraint(CC_pod, 80, name='CC Pod')
    network.add_constraint(AV_pod, 80, name='AV Pod')
    network.add_constraint(all_current, transformer_cap * 1000 / voltage, name='Transformer Cap')
    return network

## Experiment Setup

In [5]:
def experiment(algorithm):
    """ Run single phase vs. three phase experiment for a particular algorithm. """
    # -- Experiment Parameters ---------------------------------------------------
    timezone = pytz.timezone('America/Los_Angeles')
    start = timezone.localize(datetime(2018, 9, 5))
    end = timezone.localize(datetime(2018, 9, 6))
    period = 5  # minute
    voltage = 208  # volts
    default_battery_power = 32 * voltage / 1000 # kW
    site = 'caltech'

    # -- Network -------------------------------------------------------------------
    single_phase_cn = single_phase_caltech_acn(basic_evse=True, transformer_cap=70)
    real_cn = acnsim.sites.caltech_acn(basic_evse=True, transformer_cap=70)

    # -- Events ---------------------------------------------------------------------
    API_KEY = 'DEMO_TOKEN'
    events = acnsim.acndata_events.generate_events(API_KEY, site, start, end, period, 
                                                   voltage, default_battery_power)
    
    # -- Single Phase ----------------------------------------------------------------
    single_phase_sim = acnsim.Simulator(deepcopy(single_phase_cn), algorithm, 
                                        deepcopy(events), start, period=period, 
                                        verbose=False)
    single_phase_sim.run()
    
    # Since we are interested in how the single-phase LLF algorithm would have performed 
    # in the real CaltechACN, we replace the network model with the real network model 
    # for analysis. 
    single_phase_sim.network = real_cn
    
    # -- Three Phase -----------------------------------------------------------------        
    three_phase_sim = acnsim.Simulator(deepcopy(real_cn), algorithm,
                                       deepcopy(events), start, period=period, 
                                       verbose=False)
    three_phase_sim.run()
    
    return single_phase_sim, three_phase_sim

## Running Experiment

### Least Laxity First

In [6]:
llf = algorithms.SortedSchedulingAlgo(algorithms.least_laxity_first)
llf_sp_sim, llf_tp_sim = experiment(llf)

### Model Predictive Control

In [7]:
quick_charge_obj = [adacharge.ObjectiveComponent(adacharge.quick_charge),
                    adacharge.ObjectiveComponent(adacharge.equal_share, 1e-12),
                    adacharge.ObjectiveComponent(adacharge.non_completion_penalty, 1e-12),
                    ]
mpc = adacharge.AdaptiveSchedulingAlgorithm(quick_charge_obj, solver="ECOS")
mpc_sp_sim, mpc_tp_sim = experiment(mpc)

DCPError: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
0.0 + 1.0 @ [1.         0.99842271 0.99684543 0.99526814 0.99369085 0.99211356
 0.99053628 0.98895899 0.9873817  0.98580442 0.98422713 0.98264984
 0.98107256 0.97949527 0.97791798 0.97634069 0.97476341 0.97318612
 0.97160883 0.97003155 0.96845426 0.96687697 0.96529968 0.9637224
 0.96214511 0.96056782 0.95899054 0.95741325 0.95583596 0.95425868
 0.95268139 0.9511041  0.94952681 0.94794953 0.94637224 0.94479495
 0.94321767 0.94164038 0.94006309 0.9384858  0.93690852 0.93533123
 0.93375394 0.93217666 0.93059937 0.92902208 0.92744479 0.92586751
 0.92429022 0.92271293 0.92113565 0.91955836 0.91798107 0.91640379
 0.9148265  0.91324921 0.91167192 0.91009464 0.90851735 0.90694006
 0.90536278 0.90378549 0.9022082  0.90063091 0.89905363 0.89747634
 0.89589905 0.89432177 0.89274448 0.89116719 0.88958991 0.88801262
 0.88643533 0.88485804 0.88328076 0.88170347 0.88012618 0.8785489
 0.87697161 0.87539432 0.87381703 0.87223975 0.87066246 0.86908517
 0.86750789 0.8659306  0.86435331 0.86277603 0.86119874 0.85962145
 0.85804416 0.85646688 0.85488959 0.8533123  0.85173502 0.85015773
 0.84858044 0.84700315 0.84542587 0.84384858 0.84227129 0.84069401
 0.83911672 0.83753943 0.83596215 0.83438486 0.83280757 0.83123028
 0.829653   0.82807571 0.82649842 0.82492114 0.82334385 0.82176656
 0.82018927 0.81861199 0.8170347  0.81545741 0.81388013 0.81230284
 0.81072555 0.80914826 0.80757098 0.80599369 0.8044164  0.80283912
 0.80126183 0.79968454 0.79810726 0.79652997 0.79495268 0.79337539
 0.79179811 0.79022082 0.78864353 0.78706625 0.78548896 0.78391167
 0.78233438 0.7807571  0.77917981 0.77760252 0.77602524 0.77444795
 0.77287066 0.77129338 0.76971609 0.7681388  0.76656151 0.76498423
 0.76340694 0.76182965 0.76025237 0.75867508 0.75709779 0.7555205
 0.75394322 0.75236593 0.75078864 0.74921136 0.74763407 0.74605678
 0.7444795  0.74290221 0.74132492 0.73974763 0.73817035 0.73659306
 0.73501577 0.73343849 0.7318612  0.73028391 0.72870662 0.72712934
 0.72555205 0.72397476 0.72239748 0.72082019 0.7192429  0.71766562
 0.71608833 0.71451104 0.71293375 0.71135647 0.70977918 0.70820189
 0.70662461 0.70504732 0.70347003 0.70189274 0.70031546 0.69873817
 0.69716088 0.6955836  0.69400631 0.69242902 0.69085174 0.68927445
 0.68769716 0.68611987 0.68454259 0.6829653  0.68138801 0.67981073
 0.67823344 0.67665615 0.67507886 0.67350158 0.67192429 0.670347
 0.66876972 0.66719243 0.66561514 0.66403785 0.66246057 0.66088328
 0.65930599 0.65772871 0.65615142 0.65457413 0.65299685 0.65141956
 0.64984227 0.64826498 0.6466877  0.64511041 0.64353312 0.64195584
 0.64037855 0.63880126 0.63722397 0.63564669 0.6340694  0.63249211
 0.63091483 0.62933754 0.62776025 0.62618297 0.62460568 0.62302839
 0.6214511  0.61987382 0.61829653 0.61671924 0.61514196 0.61356467
 0.61198738 0.61041009 0.60883281 0.60725552 0.60567823 0.60410095
 0.60252366 0.60094637 0.59936909 0.5977918  0.59621451 0.59463722
 0.59305994 0.59148265 0.58990536 0.58832808 0.58675079 0.5851735
 0.58359621 0.58201893 0.58044164 0.57886435 0.57728707 0.57570978
 0.57413249 0.57255521 0.57097792 0.56940063 0.56782334 0.56624606
 0.56466877 0.56309148 0.5615142  0.55993691 0.55835962 0.55678233
 0.55520505 0.55362776 0.55205047 0.55047319 0.5488959  0.54731861
 0.54574132 0.54416404 0.54258675 0.54100946 0.53943218 0.53785489
 0.5362776  0.53470032 0.53312303 0.53154574 0.52996845 0.52839117
 0.52681388 0.52523659 0.52365931 0.52208202 0.52050473 0.51892744
 0.51735016 0.51577287 0.51419558 0.5126183  0.51104101 0.50946372
 0.50788644 0.50630915 0.50473186 0.50315457 0.50157729 0.5
 0.49842271 0.49684543 0.49526814 0.49369085 0.49211356 0.49053628
 0.48895899 0.4873817  0.48580442 0.48422713 0.48264984 0.48107256
 0.47949527 0.47791798 0.47634069 0.47476341 0.47318612 0.47160883
 0.47003155 0.46845426 0.46687697 0.46529968 0.4637224  0.46214511
 0.46056782 0.45899054 0.45741325 0.45583596 0.45425868 0.45268139
 0.4511041  0.44952681 0.44794953 0.44637224 0.44479495 0.44321767
 0.44164038 0.44006309 0.4384858  0.43690852 0.43533123 0.43375394
 0.43217666 0.43059937 0.42902208 0.42744479 0.42586751 0.42429022
 0.42271293 0.42113565 0.41955836 0.41798107 0.41640379 0.4148265
 0.41324921 0.41167192 0.41009464 0.40851735 0.40694006 0.40536278
 0.40378549 0.4022082  0.40063091 0.39905363 0.39747634 0.39589905
 0.39432177 0.39274448 0.39116719 0.38958991 0.38801262 0.38643533
 0.38485804 0.38328076 0.38170347 0.38012618 0.3785489  0.37697161
 0.37539432 0.37381703 0.37223975 0.37066246 0.36908517 0.36750789
 0.3659306  0.36435331 0.36277603 0.36119874 0.35962145 0.35804416
 0.35646688 0.35488959 0.3533123  0.35173502 0.35015773 0.34858044
 0.34700315 0.34542587 0.34384858 0.34227129 0.34069401 0.33911672
 0.33753943 0.33596215 0.33438486 0.33280757 0.33123028 0.329653
 0.32807571 0.32649842 0.32492114 0.32334385 0.32176656 0.32018927
 0.31861199 0.3170347  0.31545741 0.31388013 0.31230284 0.31072555
 0.30914826 0.30757098 0.30599369 0.3044164  0.30283912 0.30126183
 0.29968454 0.29810726 0.29652997 0.29495268 0.29337539 0.29179811
 0.29022082 0.28864353 0.28706625 0.28548896 0.28391167 0.28233438
 0.2807571  0.27917981 0.27760252 0.27602524 0.27444795 0.27287066
 0.27129338 0.26971609 0.2681388  0.26656151 0.26498423 0.26340694
 0.26182965 0.26025237 0.25867508 0.25709779 0.2555205  0.25394322
 0.25236593 0.25078864 0.24921136 0.24763407 0.24605678 0.2444795
 0.24290221 0.24132492 0.23974763 0.23817035 0.23659306 0.23501577
 0.23343849 0.2318612  0.23028391 0.22870662 0.22712934 0.22555205
 0.22397476 0.22239748 0.22082019 0.2192429  0.21766562 0.21608833
 0.21451104 0.21293375 0.21135647 0.20977918 0.20820189 0.20662461
 0.20504732 0.20347003 0.20189274 0.20031546 0.19873817 0.19716088
 0.1955836  0.19400631 0.19242902 0.19085174 0.18927445 0.18769716
 0.18611987 0.18454259 0.1829653  0.18138801 0.17981073 0.17823344
 0.17665615 0.17507886 0.17350158 0.17192429 0.170347   0.16876972
 0.16719243 0.16561514 0.16403785 0.16246057 0.16088328 0.15930599
 0.15772871 0.15615142 0.15457413 0.15299685 0.15141956 0.14984227
 0.14826498 0.1466877  0.14511041 0.14353312 0.14195584 0.14037855
 0.13880126 0.13722397 0.13564669 0.1340694  0.13249211 0.13091483
 0.12933754 0.12776025 0.12618297 0.12460568 0.12302839 0.1214511
 0.11987382 0.11829653 0.11671924 0.11514196 0.11356467 0.11198738
 0.11041009 0.10883281 0.10725552 0.10567823 0.10410095 0.10252366
 0.10094637 0.09936909 0.0977918  0.09621451 0.09463722 0.09305994
 0.09148265 0.08990536 0.08832808 0.08675079 0.0851735  0.08359621
 0.08201893 0.08044164 0.07886435 0.07728707 0.07570978 0.07413249
 0.07255521 0.07097792 0.06940063 0.06782334 0.06624606 0.06466877
 0.06309148 0.0615142  0.05993691 0.05835962 0.05678233 0.05520505
 0.05362776 0.05205047 0.05047319 0.0488959  0.04731861 0.04574132
 0.04416404 0.04258675 0.04100946 0.03943218 0.03785489 0.0362776
 0.03470032 0.03312303 0.03154574 0.02996845 0.02839117 0.02681388
 0.02523659 0.02365931 0.02208202 0.02050473 0.01892744 0.01735016
 0.01577287 0.01419558 0.0126183  0.01104101 0.00946372 0.00788644
 0.00630915 0.00473186 0.00315457 0.00157729] @ Sum(var1, 0, False) + 1e-12 @ -quad_over_lin(var1, 1.0) + 1e-12 @ max(norm1(Vstack((var1 @ [[208.00 208.00 ... 208.00 208.00]
 [208.00 208.00 ... 208.00 208.00]
 ...
 [208.00 208.00 ... 208.00 208.00]
 [208.00 208.00 ... 208.00 208.00]] / Promote(1000.0, (54, 634))) @ Promote(0.08333333333333333, (54, 634)), (var1 @ [[208.00 208.00 ... 208.00 208.00]
 [208.00 208.00 ... 208.00 208.00]
 ...
 [208.00 208.00 ... 208.00 208.00]
 [208.00 208.00 ... 208.00 208.00]] / Promote(1000.0, (54, 634))) @ Promote(0.08333333333333333, (54, 634)))), None, False)

## Results

In order to compare the single-phase and three-phase versions of LLF, we plot the aggregate power of all EVSEs as well as individual line currents on the primary and secondary side of the transformer which feeds the CaltechACN. 

In [ ]:
def plot_currents(single_phase_sim, three_phase_sim, transfomer_cap):
    cmap = cm.get_cmap('tab20c')

    fig, axes = plt.subplots(3, 2, sharey='row', sharex=True, figsize=(6,4))
    fig.subplots_adjust(wspace=0.17, hspace=0.17)
    axes[0, 0].set_xlim(7*12, 17*12)
    
    for i in range(3):
        for j in range(2):
            axes[i, j].spines['right'].set_visible(False)
            axes[i, j].spines['top'].set_visible(False)

    # Plot Aggregate Charging Power
    sp_agg = analysis.aggregate_current(single_phase_sim)*208/1000
    tp_agg = analysis.aggregate_current(three_phase_sim)*208/1000
    sp_color = 4
    tp_color = 0
    axes[0, 0].plot(sp_agg, color=cmap(sp_color))
    axes[0, 1].plot(tp_agg, color=cmap(tp_color))


    # Calculate currents in constrained lines
    sp_cc = analysis.constraint_currents(single_phase_sim)
    tp_cc = analysis.constraint_currents(three_phase_sim)

    # Plot currents in lines on the Primary and Secondary side of the transformer.
    for j, line in enumerate('ABC'): 
        axes[1, 0].plot(sp_cc['Primary {0}'.format(line)], label='Primary {0}'.format(line), color=cmap(j + sp_color))
        axes[1, 1].plot(tp_cc['Primary {0}'.format(line)], label='Primary {0}'.format(line), color=cmap(j + tp_color))

        axes[2, 0].plot(sp_cc['Secondary {0}'.format(line)], label='Secondary {0}'.format(line), color=cmap(j + sp_color))
        axes[2, 1].plot(tp_cc['Secondary {0}'.format(line)], label='Secondary {0}'.format(line), color=cmap(j + tp_color))

    # Plot limits 
    axes[0, 0].axhline(transfomer_cap, color='k', linestyle='--')
    axes[1, 0].axhline(transfomer_cap*1000/277/3, color='k', linestyle='--')
    axes[2, 0].axhline(transfomer_cap*1000/120/3, color='k', linestyle='--')

    axes[0, 1].axhline(transfomer_cap, color='k', linestyle='--')
    axes[1, 1].axhline(transfomer_cap*1000/277/3, color='k', linestyle='--')
    axes[2, 1].axhline(transfomer_cap*1000/120/3, color='k', linestyle='--')

    axes[0, 0].set_title("Single Phase Constraints")
    axes[0, 1].set_title("Three Phase Constriants")
    
    fig.text(0.015, 0.77, 'Aggregate\nPower (kW)', va='center', rotation='vertical')
    fig.text(0.015, 0.37, 'Line Currents (A)', va='center', rotation='vertical')
    fig.text(0.04, 0.50, 'Secondary', va='center', rotation='vertical')
    fig.text(0.04, 0.24, 'Primary', va='center', rotation='vertical')
        
    plt.xticks(range(7*12, 17*12, 36), ['7:00', '10:00', '13:00', '16:00'])
    plt.show()
    return fig

### Least Laxity First

In [ ]:
llf_fig = plot_currents(llf_sp_sim, llf_tp_sim, 70)

In [ ]:
llf_fig.savefig(f"figures/llf_single_v_three_phase.pdf", dpi=300)

### Model Predictive Control

In [ ]:
mpc_fig = plot_currents(mpc_sp_sim, mpc_tp_sim, 70)

In [ ]:
mpc_fig.savefig(f"figures/mpc_single_v_three_phase.pdf", dpi=300)

Here we can see that only considering single-phase constraints can lead to significant constraint violations in line currents for both algorithms. However, by designing an algorithm which considers the full three-phase model, we are able to respect these constraints. Note that because of phase unbalance, we are not able to make use of the full 70 kW transformer capacity while also respecting line limits using LLF. MPC allows us to fully utilize the capacity but still takes longer to deliver the same amount of energy due to contraints from phase imbalances.